//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Табель
    {
        public int Код_табеля { get; set; }
        public Nullable<int> Студент { get; set; }
        public Nullable<int> Оценка { get; set; }
        public string Присуцтвие { get; set; }
        public Nullable<int> Занятие { get; set; }
    
        public virtual Занятие Занятие1 { get; set; }
        public virtual Студент Студент1 { get; set; }
    }
}
